# Generated by Django 6.0.4 on 2026-05-04 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('v1', '0002_alter_materials_product_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='materials',
            name='attachment_1',
            field=models.FileField(blank=True, null=True, upload_to='materials/pdfs/'),
        ),
        migrations.AddField(
            model_name='materials',
            name='attachment_2',
            field=models.FileField(blank=True, null=True, upload_to='materials/pdfs/'),
        ),
        migrations.AddField(
            model_name='materials',
            name='attachment_3',
            field=models.FileField(blank=True, null=True, upload_to='materials/pdfs/'),
        ),
    ]
