# Generated by Django 6.0.4 on 2026-05-04 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('v1', '0003_materials_attachment_1_materials_attachment_2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='materials',
            name='attachment_4',
            field=models.FileField(blank=True, null=True, upload_to='materials/pdfs/'),
        ),
    ]
