# Generated by Django 6.0.4 on 2026-05-04 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('v1', '0004_materials_attachment_4'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_role',
            field=models.CharField(choices=[('ADMIN', 'ADMIN'), ('GUEST', 'GUEST'), ('REGISTERED', 'REGISTERED')], default=None, max_length=20, null=True),
        ),
    ]
