# Generated by Django 6.0.4 on 2026-05-07 07:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('v1', '0005_user_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='materials',
            name='opening_stock',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='materials',
            name='zo_material_code',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.CreateModel(
            name='InvoiceUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('invoice_number', models.CharField(blank=True, max_length=100, null=True)),
                ('customer_name', models.CharField(blank=True, max_length=255, null=True)),
                ('invoice', models.FileField(blank=True, null=True, upload_to='materials/invoice/pdfs/')),
                ('invoice_date', models.DateField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'invoice_upload',
                'verbose_name_plural': 'invoice_uploads',
                'db_table': 'invoice',
            },
        ),
        migrations.CreateModel(
            name='SoldStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('quantity_sold', models.IntegerField(blank=True, null=True)),
                ('unit_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('total_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sold_stocks', to='v1.invoiceupload')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sold_stocks', to='v1.materials')),
            ],
            options={
                'db_table': 'sold_stock',
                'ordering': ['-created_at'],
            },
        ),
    ]
